name: build
on: push
jobs:
  build:
    name: my job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12, 14]
    steps:
      - name: my first step
        env: 
          MY_VAR: Hi there! my name is
          FIRST_NAME: John
          LAST_NAME: Doe
        run: echo $MY_VAR $FIRST_NAME $LAST_NAME
